# Generated by Django 4.1.6 on 2023-02-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('postcode', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=64, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_family', to='wedding.city')),
            ],
            options={
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='InvitedGuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('family_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.family')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
    ]
