# Generated by Django 4.1.5 on 2023-02-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitedguests',
            options={'ordering': ['last_name']},
        ),
        migrations.RenameField(
            model_name='invitedguests',
            old_name='surname',
            new_name='last_name',
        ),
    ]
