# Generated by Django 4.1.5 on 2023-02-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_song_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='created',
        ),
    ]
