# Generated by Django 4.1.5 on 2023-02-17 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wedding', '0007_song_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='user_song', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
