# Generated by Django 4.1.5 on 2023-02-17 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wedding', '0008_song_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user_id',
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_song', to=settings.AUTH_USER_MODEL),
        ),
    ]
