# Generated by Django 4.1.5 on 2023-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_rename_news_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
