# Generated by Django 4.1.5 on 2023-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0014_alter_new_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
