# Generated by Django 4.1.5 on 2023-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0015_alter_new_created_alter_new_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
